/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.slf4j:slf4j-api:1.7.36")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.8.2")
}

group = "com.github.bordertech.mrz"
version = "0.9-SNAPSHOT"
description = "MRZ Java Parser"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
