name: Java CI

# Trigger workflow on push or pull_request
# Note - the first pull_request from a forked repo will need to be given approval to run
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Test and Verify
      run: ./gradlew clean build -Pdisplay-versions
