name: Java CI

# Trigger workflow on push or pull_request
# Note - the first pull_request from a forked repo will need to be given approval to run
on:
  push:
  workflow_dispatch:

env:
  AUTOPR: ${{ secrets.AUTOPR }}

jobs:
  build:
    runs-on: [self-hosted, linux, X64]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build and run tests for all applications
      run: ./gradlew publish
    - name: Bump version and push tag
      id: tag-version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: main
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag-version.outputs.new_tag }}
        files: |
          ./build/libs/mrz-java.jar
      env:
        GITHUB_TOKEN: ${{ secrets.AUTOPR }}
